# repos:
# -   repo: https://github.com/pre-commit/pre-commit-hooks
#     rev: v2.3.0
#     hooks:
#     -   id: check-yaml
#     -   id: end-of-file-fixer
#     -   id: trailing-whitespace
# -   repo: https://github.com/psf/black
#     rev: 22.10.0
#     hooks:
#     -   id: black


# repos:
# -   repo: local
#     hooks:
#     -   id: run_e2e_tests
#         name: Run e2e-tests
#         entry: pnpm turbo e2e-tests run_e2e_tests
#         language: unsupported
#         # types: python
#         stages: [pre-commit, pre-push, manual]
#         # require_serial: true

        
#     # -   id: check-x
#     #     name: Check X 
#     #     entry: ./bin/check-x.sh
#     #     language: unsupported_script
#     #     files: \.x$
#     # -   id: scss-lint
#     #     name: scss-lint
#     #     entry: scss-lint
#     #     language: ruby
#     #     language_version: 2.1.5
#     #     types: [scss]
#     #     additional_dependencies: ['scss_lint:0.52.0']




repos:
# -   repo: https://github.com/pre-commit/pre-commit-hooks
#     rev: v2.3.0
#     hooks:
#     -   id: check-yaml
#     -   id: end-of-file-fixer
#     -   id: trailing-whitespace
# -   repo: https://github.com/psf/black
#     rev: 22.10.0
#     hooks:
#     -   id: black

-   repo: local
    hooks:
      - id: run-e2e-tests
        name:  Run e2e-tests
        entry: pnpm 
        language: system
        # types: [python]
        args: ["turbo","e2e-tests"]
        pass_filenames: false
        always_run: true
        stages: [pre-push]
