exclude: |
  (?x)^(
      .*cache.*/.*|       # Exclude cache directories
      .*venv.*/.*|        # Exclude virtual environment directories
      .*pnpm-store.*/.*|  # Exclude dependency directories
      .pnpm-lock.yaml
  )$
# fail_fast: true # stop running hooks after the first failure.
default_install_hook_types:
  - pre-commit
  - pre-push
repos:

  # ------------------------------ Security Checks ------------------------------ #

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.30.0
    hooks:
      - id: gitleaks
        name: "Check for secret leaks"
        stages: [pre-commit, pre-push, manual]

  # ----------------------------- Code Quality Checks ---------------------------- #

  # Auto-format and lint Python with Ruff
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.5
    hooks:
      - id: ruff-check
        args: [--fix]
        name: "Lint Python with Ruff"
        stages: [pre-push, manual]
      - id: ruff-format
        name: "Format Python with Ruff"
        stages: [pre-push, manual]

  # Format with Prettier
  - repo: local
    hooks:
      - id: prettier-check
        name: "Format ts, md, css, mjs, json with prettier"
        language: system
        pass_filenames: false
        always_run: true
        entry: |
          npx prettier --check --write --trailing-comma=all '**/*.{md,js,jsx,ts,tsx,css,scss}'
        stages: [pre-push, manual]

  # Lint with ESLint
  - repo: local
    hooks:
      - id: eslint
        name: "Run ESLint"
        pass_filenames: false
        always_run: true
        language: system
        entry: pnpm lint
        stages: [pre-commit, pre-push, manual]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml # Attempts to load all YAML files to verify syntax
        name: "Validate YAML syntax"
      - id: end-of-file-fixer # Ensures files end with a single newline
        name: "Fix end-of-file newlines"
      - id: trailing-whitespace # Trims trailing whitespace
        name: "Trim trailing whitespace"

  # Shell
  - repo: https://github.com/openstack/bashate
    rev: 2.1.1
    hooks:
      - id: bashate
        name: "Check shell script style"
        stages: [pre-commit, pre-push, manual]

  # ------------------------------- Local Fast Tests ------------------------------ #

  - repo: local
    hooks:
      - id: run-e2e-tests
        name: "Run E2E tests"
        entry: pnpm
        language: system
        args: ["turbo", "test:e2e"]
        pass_filenames: false
        always_run: true
        stages: [pre-push, manual]
