import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Footer from "@sellify/customer-ui-components/footer/Footer";

import { getCartItems } from "common/actions/cart-actions";
import SearchPanelProvider from "common/providers/SearchPanelProvider";
import CartPanelProvider from "common/providers/CartPanelProvider";
import ProductAddedDialogProvider from "common/providers/ProductAddedDialogProvider";
import Header from "components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="size-full">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased size-full flex flex-col relative items-center`}
      >
        <SearchPanelProvider>
          <CartPanelProvider>
            <Header />
            <main className="flex grow w-full justify-center relative flex-shrink-0 mt-20 px-9 md:px-14 pt-9 pb-14 max-w-7xl">
              <ProductAddedDialogProvider>
                {children}
              </ProductAddedDialogProvider>
            </main>
            <Footer copyright="Long company name" />
          </CartPanelProvider>
        </SearchPanelProvider>
      </body>
    </html>
  );
}
