import type { Metadata } from "next";
import { Geist, Geist_Mono, Playfair_Display, DM_Sans } from "next/font/google";
import "./globals.css";

import Footer from "@sellify/customer-ui-components/footer/Footer";

import Header from "components/header/Header";
import SearchPanelProvider from "common/providers/SearchPanelProvider";
import CartPanelProvider from "common/providers/CartPanelProvider";
import AlertDialogProvider from "common/providers/AlertDialogProvider";
import DestructiveAlertDialogProvider from "common/providers/RiskDialogProvider";
import NavbarDrawerProvider from "common/providers/NavbarDrawerProvider";
import FilterPanelProvider from "common/providers/FilterPanelProvider";

const playfairDisplay = Playfair_Display({
  variable: "--font-heading-family",
  subsets: ["latin"],
  style: "normal",
  weight: "400",
});

const playfairDisplayMedium = Playfair_Display({
  variable: "--font-heading-family-medium",
  subsets: ["latin"],
  style: "normal",
  weight: "500",
});

const DMSans = DM_Sans({
  variable: "--font-body-family",
  subsets: ["latin"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`size-full ${playfairDisplay.variable} ${DMSans.variable} ${playfairDisplayMedium.variable}`}
    >
      <body
        className={`antialiased size-full flex flex-col relative items-center`}
      >
        <DestructiveAlertDialogProvider>
          <AlertDialogProvider>
            <NavbarDrawerProvider>
              <SearchPanelProvider>
                <FilterPanelProvider>
                  <CartPanelProvider>
                    <Header />
                    {children}
                    <Footer copyright="Long company name" />
                  </CartPanelProvider>
                </FilterPanelProvider>
              </SearchPanelProvider>
            </NavbarDrawerProvider>
          </AlertDialogProvider>
        </DestructiveAlertDialogProvider>
      </body>
    </html>
  );
}
