import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";
import Footer from "@sellify/admin-ui-components/Footer";

import RiskDialogProvider from "providers/RiskDialogProvider";
import AlertDialogProvider from "providers/AlertDialogProvider";
import FilterPanelProvider from "providers/FilterPanelProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`size-full ${geistSans.variable} ${geistMono.variable}`}
    >
      <body
        className={`antialiased size-full flex flex-col relative items-center `}
      >
        <RiskDialogProvider>
          <AlertDialogProvider>
            <FilterPanelProvider>
              {children}
              <Footer copyright="Long company name" />
            </FilterPanelProvider>
          </AlertDialogProvider>
        </RiskDialogProvider>
      </body>
    </html>
  );
}
