import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";
import Footer from "components/Footer";
import MainMenu from "components/main-menu/MainMenu";
import MainMenuDrawer from "components/main-menu/MainMenuDrawer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`size-full ${geistSans.variable} ${geistMono.variable}`}
    >
      <body
        className={`antialiased size-full flex flex-col relative items-center `}
      >
        <div className="flex w-full lg:hidden px-8 pt-12">
          <MainMenuDrawer />
        </div>
        <div className="flex grow w-full justify-center relative flex-shrink-0 px-8 pt-12 max-w-7xl">
          <div className="flex-none w-64 not-lg:hidden py-4">
            <MainMenu />
          </div>
          <main className="flex flex-1 flex-col gap-8 h-full overflow-x-auto">
            {children}
          </main>
        </div>
        <Footer copyright="Long company name" />
      </body>
    </html>
  );
}
