name: CI
on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, reopened, close]
jobs:
  container-run-tests:
    runs-on: ubuntu-latest
    container: xamarsia/sellify/ci:0.0.0
    steps:
      - name: Install all dependencies for the project
        run: pnpm install

      - name: Run all e2e tests
        run: pnpm turbo e2e-tests
