name: CI
on:
  push:
  pull_request:
    types: [opened, reopened, close]
jobs:
  container-run-tests:
    runs-on: ubuntu-latest
    container: xamarsia/sellify-ci:0.0.1
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: pre-commit/action@v3.0.1
        # with:
        #   sparse-checkout: |
        #     packages
        #     examples
        #     scripts

      - name: Install all dependencies for the project
        run: pnpm install && git init

      - name: Activate the CD virtual environment
        run: . scripts/ci-envsetup.sh && pwd && ls && pre-commit run --all-files --hook-stage manual
